name: Multi Env Infra Deployment Workflow

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: repo
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Whatif: Development'
      run: |
        az deployment group what-if \
          --resource-group dev-application-rg \
          --template-file ./repo/chapter-9/app.bicep \
          --parameters ./repo/chapter-9/parameters-dev.json
    - name: 'Deploy: Development'
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'dev-application-rg'
        template: ./repo/chapter-9/app.bicep
        parameters: ./repo/chapter-9/parameters-dev.json
      if: success()

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-development
    steps:
    - uses: actions/checkout@v3
      with:
        path: repo
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.PRODUCTION_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.PRODUCTION_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID }}
    - name: 'Whatif: Production'
      run: |
        az deployment group what-if \
          --resource-group production-application-rg \
          --template-file ./repo/chapter-9/app.bicep \
          --parameters ./repo/chapter-9/parameters-production.json
    - name: 'Deploy: Production'
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'production-application-rg'
        template: ./repo/chapter-9/app.bicep
        parameters: ./repo/chapter-9/parameters-production.json
      if: success()
